name: CI Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Test Code Coverage with nosetests
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Set up Sphinx
        run: |
          mkdir -p docs
          cat <<EOF > docs/conf.py
          extensions = ['sphinx.ext.autodoc']
          project = 'Your Project Name'
          author = 'Your Name'
          html_theme = 'alabaster'
          html_build_dir = '_build/html'
          master_doc = 'index'
          EOF
    
      - name: Generate Documentation
        run: |
          sphinx-quickstart -q -p docs
          sphinx-apidoc -o docs/source src
          make -C docs clean
          make -C docs html
        
      - name: Code Analysis with Bandit
        run: |
          pip install bandit
          bandit -r src -lll
